language: ruby
rvm:
  - 2.3.8
  - 2.4.7
  - 2.5.6
  - 2.6.4
  - ruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
before_install: gem install bundler -v 1.12.5
script:
  - bundle exec rake
  - bundle exec rubocop
