language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2.2
  - ruby-head
  - jruby-19mode
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: rbx-2
before_install: gem install bundler -v 1.10.5
script:
  - bundle exec rake
  - bundle exec rubocop
