language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2.8
  - 2.3.6
  - 2.4.3
  - ruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
before_install: gem install bundler -v 1.12.5
script:
  - bundle exec rake
  - bundle exec rubocop
